### ISSUE TITLE
Chunk test reporting

### ISSUE THREAD

**Issue by nathanboktae** [tolbertam/mocha-appveyor-reporter#1]
Currently the reporter only sends all the tests at once at the end. This won't scale - batching the tests to report 100 at a time would be good.

**Comment by nathanboktae** [comment]
Probably not needed after #5

**Comment by tolbertam** [comment]
Closing this for now, but may possibly revisit it if it's determined reporting after each test completion is too much for appveyor (so far so good).

**Comment by tolbertam** [comment]
Batched reporting introduced in #12, reports are now batched for every 100 tests or 1 second elapsed (whichever happens first),  this is also configurable, so a user can disable it completely or increase the batch intervals.
