### ISSUE TITLE
Tests are recorded in the incorrect order

### ISSUE THREAD

**Issue by MarshallOfSound** [tolbertam/mocha-appveyor-reporter#11]
Because tests are sent through HTTP which is asyncronous the tests appear on AppVeyor out of order.

Preferably the reporter should wait for the previous test to send before sending the next one.  This guarantees order and if implemented correctly may fix #9

**Comment by tolbertam** [comment]
👍 , it would be nice to ensure tests are done in order.  Will add this to the next milestone.

**Comment by tolbertam** [comment]
Just realized, I think what we may be seeing is that Appveyor itself does not report tests in any meaningful order, so unfortunately there is no way to control it from this plugin.  I'll keep my eye on appveyor/ci#239.

**Comment by tolbertam** [comment]
Removed the milestone, since I think it's reasonable to keep this ticket open until there's a good solution for this.

**Comment by tolbertam** [comment]
Revisiting this, since after #9 tests are reported in order of completion, there is not much more the reporter can do since AppVeyor itself is not maintaining the order.  Feel free to reopen if there is something we can do here to fix that.
